apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample-v1
  namespace: default
  labels:
    app: nginx-sample
    version: v1
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-sample
      version: v1
  template:
    metadata:
      labels:
        app: nginx-sample
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
